### ISSUE TITLE
Unknown error retrieving IP.

### ISSUE THREAD

**Issue by juliensnz** [Arubacloud/pyArubaCloud#12]
Hello,

When I try to create a new vm I get this error: 

```
Traceback (most recent call last):
  File "./examples/create_pro_vm.py", line 20, in <module>
    ip = i.purchase_ip()
  File "/usr/local/lib/python2.7/site-packages/ArubaCloud/PyArubaAPI.py", line 251, in purchase_ip
    raise Exception('Unknown error retrieving IP.')
Exception: Unknown error retrieving IP.
```

Here is the command I typed:

`python ./examples/create_pro_vm.py -d 4 -u my_login -w my_password -t 35 -n aruba-vps-0004 --vmpassword vmpass`

**Comment by blackms** [comment]
Hi @juliensnz, 
In order to debug the problem I need to add more verbosity to the method, I'm going to do it now, but meanwhile could you check if you have enough credit to buy a new IP or if you have a total of 15 IP per vm? Because there is this limit: if you have 1 vm you can buy up to 15 ip, 30 in case of two vm and so on...

Furthermore, the template with ID 35 within datacenter 4 should be a Windows 2003, it's not possible to create a Windows 2003 VM anymore, since Microsoft ended the support. Actually this is not visible in the template object, I'm going to add the "enabled" field tomorrow.

**Comment by blackms** [comment]
Hello,
I made the changes, please try running it with parameter debug=True in purchase_ip (already in the example), and let me know what is the error message returned.
